### ISSUE TITLE
 Make use of more AWS services

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/xnat-aws#3]
Currently we are doing a  lot of configuration of the ec2 instances with Ansible. Some of this could be removed and replaced with AWS managed services, e.g.:

- remove the database ec2 instance and use [RDS](https://aws.amazon.com/rds/postgresql/)
- ~~remove the web server ec2 instance and use [Elastic Beanstalk](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/java-tomcat-platform.html)~~
- once the Container Service is working (#6), look into using [ECS](https://aws.amazon.com/ecs/) to run the containers
```[tasklist]
### Tasks
- [ ] https://github.com/UCL-MIRSG/xnat-aws/issues/25
- [ ] https://github.com/UCL-MIRSG/xnat-aws/issues/26
- [ ] https://github.com/UCL-MIRSG/xnat-aws/issues/27
```

**Comment by p-j-smith** [comment]
closing as it's now essentially a duplicate of #27
