### ISSUE TITLE
Add more detailed user documentation

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/xnat-aws#4]
There are currently some READMEs with a general overview of how to deploy XNAT on AWS, but we need a more detailed docs / user guide
```[tasklist]
### Tasks
- [ ] https://github.com/UCL-MIRSG/xnat-aws/issues/40
- [ ] https://github.com/UCL-MIRSG/xnat-aws/issues/39
- [ ] https://github.com/UCL-MIRSG/xnat-aws/issues/42
```
