### ISSUE TITLE
Test infrastructure with example workshop

### ISSUE THREAD

**Issue by milanmlft** [UCL-MIRSG/xnat-aws#44]
Use https://healthbioscienceideas.github.io/MedICSS-Project-Repro-Pipelines/
```[tasklist]
### Tasks
- [ ] https://github.com/UCL-MIRSG/xnat-aws/issues/70
- [ ] https://github.com/UCL-MIRSG/xnat-aws/issues/71
- [ ] https://github.com/UCL-MIRSG/xnat-aws/issues/74
```

**Comment by milanmlft** [comment]
Apart from #70, everything else seems to be working now.
Next step would be to let multiple people run the workshop simultaneously and see if the infrastructure can handle the traffic.
